# Generated by Django 3.0.14 on 2022-08-04 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_mutations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='ServiceService',
            fields=[
                ('id', models.AutoField(db_column='idSCP', default=1, primary_key=True, serialize=False)),
                ('qty_provided', models.IntegerField(blank=True, db_column='qty', null=True)),
                ('scpDate', models.DateTimeField(blank=True, db_column='created_date', default=django.utils.timezone.now, null=True)),
                ('price_asked', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=18, null=True)),
                ('service', models.ForeignKey(db_column='ServiceId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicesServices', to='medical.Service')),
                ('servicelinkedService', models.ForeignKey(db_column='ServiceLinked', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medical.Service')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblServiceContainedPackage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(db_column='idPCP', default=1, primary_key=True, serialize=False)),
                ('qty_provided', models.IntegerField(blank=True, db_column='qty', null=True)),
                ('pcpDate', models.DateTimeField(blank=True, db_column='created_date', default=django.utils.timezone.now, null=True)),
                ('price_asked', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=18, null=True)),
                ('item', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemsServices', to='medical.Item')),
                ('servicelinkedItem', models.ForeignKey(db_column='ServiceID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicesLinked', to='medical.Service')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblProductContainedPackage',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='manualPrice',
            field=models.BooleanField(default=False),
        ),
    ]
