# Generated by Django 3.0.14 on 2022-07-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_mutations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True},
        ),
    ]
