# Generated by Django 3.0.14 on 2022-08-04 12:31

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20220804_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceservice',
            old_name='scpPrice',
            new_name='price_asked',
        ),
        migrations.RenameField(
            model_name='serviceservice',
            old_name='scpQuantity',
            new_name='qty_provided',
        ),
        migrations.AddField(
            model_name='serviceservice',
            name='servicelinked',
            field=models.ForeignKey(db_column='ServiceLinked', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medical.Service'),
            preserve_default=False,
        ),

    ]
