# Generated by Django 3.0.14 on 2022-07-26 18:34

import core.fields
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20220725_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='manualPrice',
            field=models.BooleanField(default=False),
        )
    ]
