# Generated by Django 3.2.16 on 2023-07-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_set_managed_to_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='maximum_amount',
            field=models.DecimalField(db_column='MaximumAmount', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='maximum_amount',
            field=models.DecimalField(db_column='MaximumAmount', decimal_places=2, max_digits=18, null=True),
        ),
    ]
