# Generated by Django 3.0.14 on 2022-08-04 14:10

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20220804_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='item_id',
            field=models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemsServices', to='medical.Item'),
        ),
    ]
