# Generated by Django 3.0.14 on 2022-08-29 21:02

import core.fields
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_auto_20230730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pat_cat',
        ),
        migrations.RemoveField(
            model_name='service',
            name='row_id',
        ),
        migrations.AddField(
            model_name='service',
            name='packagetype',
            field=models.CharField(db_column='ServPackageType', default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='service',
            name='patient_category',
            field=models.SmallIntegerField(db_column='ServPatCat', default='15'),
        ),
        migrations.AddField(
            model_name='service',
            name='uuid',
            field=models.CharField(db_column='ServiceUUID', default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='validity_from',
            field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        ),
    ]
