# Generated by Django 3.0.14 on 2022-07-26 18:52

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_auto_20220726_1834'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='ServiceContainedPackage',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('idSCP', models.AutoField(primary_key=True, serialize=False)),
                ('SCPQuantity', models.IntegerField(blank=True, db_column='PackageQuantity', null=True)),
                ('SCPDate', models.DateTimeField(blank=True, db_column='PackageDate', null=True)),
                ('SCPPrice', models.DecimalField(blank=True, db_column='PackagePrice', decimal_places=2, max_digits=18, null=True)),
                ('medical_serviceId', models.ForeignKey(db_column='ServiceID', on_delete=django.db.models.deletion.DO_NOTHING, to='medical.Service')),
            ],
            options={
                'db_table': 'tblServiceContainedPackage',
                'managed': True,
            },
        ),
    ]
