# Generated by Django 3.2.20 on 2023-07-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_set_managed_to_true'),
        ('medical', '0008_auto_20220805_2108'),
    ]

    operations = [
    ]
