# Generated by Django 3.2.24 on 2024-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_auto_20220804_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='patient_category',
            field=models.SmallIntegerField(db_column='ServPatCat', default=15),
        ),
    ]
