# Generated by Django 4.2.11 on 2024-09-23 14:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_service_patient_category'),
    ]

    operations = [
        # Suppression des vues existantes, sans générer d'erreur si elles n'existent pas
        migrations.RunSQL(
            'DROP VIEW IF EXISTS "public"."uvwServiceExpenditures";'
        ),
        migrations.RunSQL(
            'DROP VIEW IF EXISTS "public"."uvwServiceUtilization";'
        ),
        migrations.RunSQL(
            'DROP VIEW IF EXISTS "public"."uvwItemExpenditures";'
        ),
        migrations.RunSQL(
            'DROP VIEW IF EXISTS "public"."uvwItemUtilization";'
        ),
    ]
