# Generated by Django 3.2.20 on 2026-02-12 16:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20230315_0851'),
        ('medical', '0010_rename_servicelinkeditem_serviceitem_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='program',
            field=models.ForeignKey(db_column='program', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_program', to='program.program'),
        ),
        migrations.AddField(
            model_name='service',
            name='program',
            field=models.ForeignKey(db_column='program', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_program', to='program.program'),
        ),
    ]
